// src/app/pages/contact/contact.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';

interface ContactForm {
  name: string;
  email: string;
  subject: string;
  message: string;
}

@Component({
  selector: 'app-contact',
  standalone: true,
  imports: [CommonModule, FormsModule],
  template: `
    <div class="contact-page">
      <div class="container">
        <div class="page-header text-center mb-8">
          <h1 class="page-title fade-in">Contactez-nous</h1>
          <p class="page-description fade-in">
            Nous sommes là pour répondre à toutes vos questions
          </p>
        </div>

        <div class="contact-content">
          <div class="grid grid-cols-1 md:grid-cols-2">
            <!-- Formulaire de contact -->
            <div class="contact-form-section fade-in">
              <div class="card">
                <h2 class="form-title">Envoyez-nous un message</h2>
                <form (ngSubmit)="onSubmit()" #contactForm="ngForm" class="contact-form">
                  <div class="form-group">
                    <label for="name" class="form-label">Nom complet</label>
                    <input
                      type="text"
                      id="name"
                      name="name"
                      [(ngModel)]="formData.name"
                      required
                      class="form-input"
                      placeholder="Votre nom complet"
                    >
                  </div>

                  <div class="form-group">
                    <label for="email" class="form-label">Email</label>
                    <input
                      type="email"
                      id="email"
                      name="email"
                      [(ngModel)]="formData.email"
                      required
                      class="form-input"
                      placeholder="votre@email.com"
                    >
                  </div>

                  <div class="form-group">
                    <label for="subject" class="form-label">Sujet</label>
                    <input
                      type="text"
                      id="subject"
                      name="subject"
                      [(ngModel)]="formData.subject"
                      required
                      class="form-input"
                      placeholder="Sujet de votre message"
                    >
                  </div>

                  <div class="form-group">
                    <label for="message" class="form-label">Message</label>
                    <textarea
                      id="message"
                      name="message"
                      [(ngModel)]="formData.message"
                      required
                      rows="5"
                      class="form-textarea"
                      placeholder="Votre message..."
                    ></textarea>
                  </div>

                  <button
                    type="submit"
                    [disabled]="!contactForm.form.valid || isSubmitting"
                    class="btn btn-primary submit-btn"
                  >
                    {{ isSubmitting ? 'Envoi en cours...' : 'Envoyer le message' }}
                  </button>
                </form>

                <div *ngIf="submitMessage" class="submit-message" [class.success]="submitSuccess">
                  {{ submitMessage }}
                </div>
              </div>
            </div>

            <!-- Informations de contact -->
            <div class="contact-info-section fade-in">
              <div class="contact-info">
                <h2 class="info-title">Nos coordonnées</h2>
                
                <div class="info-item" *ngFor="let info of contactInfo">
                  <div class="info-icon">{{ info.icon }}</div>
                  <div class="info-content">
                    <h3 class="info-label">{{ info.label }}</h3>
                    <p class="info-value">{{ info.value }}</p>
                  </div>
                </div>
              </div>

              <div class="business-hours">
                <h3 class="hours-title">Horaires d'ouverture</h3>
                <div class="hours-list">
                  <div class="hours-item" *ngFor="let hour of businessHours">
                    <span class="day">{{ hour.day }}</span>
                    <span class="time">{{ hour.time }}</span>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  `,
  styles: [`
    .contact-page {
      padding: 2rem 0 4rem;
    }

    .page-title {
      font-size: 3rem;
      font-weight: 700;
      color: var(--text-primary);
      margin-bottom: 1rem;
    }

    .page-description {
      font-size: 1.25rem;
      color: var(--text-secondary);
      max-width: 600px;
      margin: 0 auto;
    }

    .contact-content {
      margin-top: 3rem;
    }

    .form-title {
      font-size: 1.5rem;
      font-weight: 600;
      color: var(--text-primary);
      margin-bottom: 2rem;
    }

    .contact-form {
      display: flex;
      flex-direction: column;
      gap: 1.5rem;
    }

    .form-group {
      display: flex;
      flex-direction: column;
    }

    .form-label {
      font-weight: 500;
      color: var(--text-primary);
      margin-bottom: 0.5rem;
    }

    .form-input,
    .form-textarea {
      padding: 0.75rem;
      border: 1px solid var(--border-color);
      border-radius: 0.5rem;
      font-size: 1rem;
      transition: border-color 0.3s ease, box-shadow 0.3s ease;

      &:focus {
        outline: none;
        border-color: var(--primary-color);
        box-shadow: 0 0 0 3px rgba(59, 130, 246, 0.1);
      }
    }

    .form-textarea {
      resize: vertical;
      min-height: 120px;
    }

    .submit-btn {
      margin-top: 1rem;
      
      &:disabled {
        opacity: 0.6;
        cursor: not-allowed;
      }
    }

    .submit-message {
      margin-top: 1rem;
      padding: 0.75rem;
      border-radius: 0.5rem;
      background: var(--error-color);
      color: white;
      text-align: center;

      &.success {
        background: var(--success-color);
      }
    }

    .contact-info {
      margin-bottom: 2rem;
    }

    .info-title {
      font-size: 1.5rem;
      font-weight: 600;
      color: var(--text-primary);
      margin-bottom: 2rem;
    }

    .info-item {
      display: flex;
      align-items: flex-start;
      gap: 1rem;
      margin-bottom: 1.5rem;
    }

    .info-icon {
      font-size: 1.5rem;
      width: 2.5rem;
      height: 2.5rem;
      background: var(--primary-color);
      color: white;
      border-radius: 50%;
      display: flex;
      align-items: center;
      justify-content: center;
      flex-shrink: 0;
    }

    .info-label {
      font-weight: 600;
      color: var(--text-primary);
      margin-bottom: 0.25rem;
    }

    .info-value {
      color: var(--text-secondary);
    }

    .business-hours {
      background: var(--background-color);
      padding: 1.5rem;
      border-radius: 0.75rem;
    }

    .hours-title {
      font-size: 1.25rem;
      font-weight: 600;
      color: var(--text-primary);
      margin-bottom: 1rem;
    }

    .hours-item {
      display: flex;
      justify-content: space-between;
      padding: 0.5rem 0;
      border-bottom: 1px solid var(--border-color);

      &:last-child {
        border-bottom: none;
      }
    }

    .day {
      font-weight: 500;
      color: var(--text-primary);
    }

    .time {
      color: var(--text-secondary);
    }

    @media (max-width: 768px) {
      .page-title {
        font-size: 2rem;
      }

      .contact-content {
        margin-top: 2rem;
      }
    }
  `]
})
export class ContactComponent {
  formData: ContactForm = {
    name: '',
    email: '',
    subject: '',
    message: ''
  };

  isSubmitting = false;
  submitMessage = '';
  submitSuccess = false;

  contactInfo = [
    {
      icon: '📧',
      label: 'Email',
      value: 'contact@monsite.com'
    },
    {
      icon: '📞',
      label: 'Téléphone',
      value: '+33 1 23 45 67 89'
    },
    {
      icon: '📍',
      label: 'Adresse',
      value: '123 Rue de la Paix, 75001 Paris, France'
    }
  ];

  businessHours = [
    { day: 'Lundi - Vendredi', time: '9h00 - 18h00' },
    { day: 'Samedi', time: '10h00 - 16h00' },
    { day: 'Dimanche', time: 'Fermé' }
  ];

  onSubmit() {
    if (this.isSubmitting) return;

    this.isSubmitting = true;
    this.submitMessage = '';

    // Simulation d'envoi de formulaire
    setTimeout(() => {
      this.isSubmitting = false;
      this.submitSuccess = true;
      this.submitMessage = 'Votre message a été envoyé avec succès ! Nous vous répondrons dans les plus brefs délais.';
      
      // Reset du formulaire
      this.formData = {
        name: '',
        email: '',
        subject: '',
        message: ''
      };

      // Effacer le message après 5 secondes
      setTimeout(() => {
        this.submitMessage = '';
      }, 5000);
    }, 2000);
  }
}

// src/components/Contact.tsx
import React, { useState } from 'react';
import { motion } from 'framer-motion';
import { useScrollAnimation } from '../hooks/useScrollAnimation';
import { 
  Mail, 
  Phone, 
  MapPin, 
  Linkedin, 
  Github, 
  Twitter,
  Check,
  Loader2
} from 'lucide-react';

interface FormData {
  name: string;
  email: string;
  subject: string;
  message: string;
}

const Contact: React.FC = () => {
  const [formData, setFormData] = useState<FormData>({
    name: '',
    email: '',
    subject: '',
    message: ''
  });
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [submitted, setSubmitted] = useState(false);
  
  const titleAnimation = useScrollAnimation();
  const formAnimation = useScrollAnimation(0.1, 0.2);
  const infoAnimation = useScrollAnimation(0.1, 0.4);
  
  const handleChange = (
    e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement>
  ) => {
    const { name, value } = e.target;
    setFormData(prev => ({ ...prev, [name]: value }));
  };
  
  const handleSubmit = async (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    setIsSubmitting(true);
    
    try {
      // Simulate API call
      await new Promise(resolve => setTimeout(resolve, 1500));
      
      setSubmitted(true);
      setFormData({
        name: '',
        email: '',
        subject: '',
        message: ''
      });
      
      setTimeout(() => setSubmitted(false), 5000);
    } finally {
      setIsSubmitting(false);
    }
  };

  const contactInfo = [
    {
      icon: <Mail className="h-5 w-5 text-primary-500" />,
      title: "Email",
      content: (
        <a 
          href="mailto:inovex-solution@gmail.com" 
          className="hover:text-primary-500 transition-colors"
        >
          inovex-solution@gmail.com
        </a>
      )
    },
    {
      icon: <Phone className="h-5 w-5 text-primary-500" />,
      title: "Téléphone",
      content: (
        <a 
          href="tel:+22654487985" 
          className="hover:text-primary-500 transition-colors"
        >
          +226 54 48 79 85
        </a>
      )
    },
    {
      icon: <MapPin className="h-5 w-5 text-primary-500" />,
      title: "Adresse",
      content: "Ouaga 2000, 01 BP 120, OUAGADOUGOU"
    }
  ];

  const socialLinks = [
    {
      icon: <Linkedin className="h-5 w-5" />,
      label: "LinkedIn",
      url: "#"
    },
    {
      icon: <Github className="h-5 w-5" />,
      label: "GitHub",
      url: "#"
    },
    {
      icon: <Twitter className="h-5 w-5" />,
      label: "Twitter",
      url: "#"
    }
  ];

  const subjects = [
    "Développement Web & Mobile",
    "Cloud & DevOps",
    "Agents Intelligents (IA)",
    "Domotique & IoT",
    "Cybersécurité",
    "Conseil Technologique",
    "Autre sujet"
  ];

  return (
    <section id="contact" className="py-20 bg-gray-50 dark:bg-dark-900">
      <div className="container px-4 mx-auto max-w-7xl">
        <motion.div 
          className="text-center mb-16"
          ref={titleAnimation.ref}
          initial="hidden"
          animate={titleAnimation.controls}
          variants={titleAnimation.variants}
        >
          <h2 className="text-4xl font-bold mb-4 text-dark-900 dark:text-white">
            Contactez-nous
          </h2>
          <p className="text-lg text-gray-600 dark:text-gray-300 max-w-2xl mx-auto">
            Discutons de votre projet et découvrons comment nous pouvons vous aider
          </p>
        </motion.div>

        <div className="grid grid-cols-1 lg:grid-cols-2 gap-12">
          {/* Contact Information */}
          <motion.div
            ref={infoAnimation.ref}
            initial="hidden"
            animate={infoAnimation.controls}
            variants={infoAnimation.variants}
          >
            <div className="bg-white dark:bg-dark-800 rounded-2xl shadow-lg p-8 h-full">
              <h3 className="text-2xl font-semibold mb-8 text-dark-900 dark:text-white">
                Informations de contact
              </h3>
              
              <div className="space-y-6">
                {contactInfo.map((item, index) => (
                  <div key={index} className="flex items-start gap-4">
                    <div className="bg-primary-100 dark:bg-primary-900/20 p-3 rounded-full">
                      {item.icon}
                    </div>
                    <div>
                      <h4 className="text-lg font-medium text-dark-800 dark:text-gray-200">
                        {item.title}
                      </h4>
                      <p className="text-gray-600 dark:text-gray-400 mt-1">
                        {item.content}
                      </p>
                    </div>
                  </div>
                ))}
              </div>
              
              <div className="mt-12">
                <h4 className="text-lg font-medium mb-4 text-dark-800 dark:text-gray-200">
                  Suivez-nous
                </h4>
                <div className="flex gap-3">
                  {socialLinks.map((social, index) => (
                    <a
                      key={index}
                      href={social.url}
                      className="h-10 w-10 rounded-full bg-gray-100 dark:bg-dark-700 flex items-center justify-center text-gray-700 dark:text-gray-300 hover:bg-primary-500 hover:text-white transition-colors"
                      aria-label={social.label}
                    >
                      {social.icon}
                    </a>
                  ))}
                </div>
              </div>
            </div>
          </motion.div>
          
          {/* Contact Form */}
          <motion.div
            ref={formAnimation.ref}
            initial="hidden"
            animate={formAnimation.controls}
            variants={formAnimation.variants}
          >
            {submitted ? (
              <div className="bg-white dark:bg-dark-800 rounded-2xl shadow-lg p-8 h-full flex flex-col items-center justify-center text-center">
                <div className="w-20 h-20 rounded-full bg-green-100 dark:bg-green-900/20 flex items-center justify-center mb-6">
                  <Check className="w-10 h-10 text-green-500" />
                </div>
                <h3 className="text-2xl font-semibold mb-2 text-dark-900 dark:text-white">
                  Message envoyé!
                </h3>
                <p className="text-gray-600 dark:text-gray-400">
                  Merci pour votre message. Nous vous répondrons rapidement.
                </p>
              </div>
            ) : (
              <form 
                onSubmit={handleSubmit} 
                className="bg-white dark:bg-dark-800 rounded-2xl shadow-lg p-8"
              >
                <h3 className="text-2xl font-semibold mb-8 text-dark-900 dark:text-white">
                  Envoyez-nous un message
                </h3>
                
                <div className="space-y-6">
                  <div>
                    <label 
                      htmlFor="name" 
                      className="block text-sm font-medium mb-2 text-gray-700 dark:text-gray-300"
                    >
                      Nom complet
                    </label>
                    <input
                      type="text"
                      id="name"
                      name="name"
                      value={formData.name}
                      onChange={handleChange}
                      required
                      className="w-full px-4 py-3 rounded-lg border border-gray-300 dark:border-dark-700 focus:ring-2 focus:ring-primary-500 focus:border-transparent bg-white dark:bg-dark-900 transition-all"
                      placeholder="Votre nom"
                    />
                  </div>
                  
                  <div>
                    <label 
                      htmlFor="email" 
                      className="block text-sm font-medium mb-2 text-gray-700 dark:text-gray-300"
                    >
                      Email
                    </label>
                    <input
                      type="email"
                      id="email"
                      name="email"
                      value={formData.email}
                      onChange={handleChange}
                      required
                      className="w-full px-4 py-3 rounded-lg border border-gray-300 dark:border-dark-700 focus:ring-2 focus:ring-primary-500 focus:border-transparent bg-white dark:bg-dark-900 transition-all"
                      placeholder="votre@email.com"
                    />
                  </div>
                  
                  <div>
                    <label 
                      htmlFor="subject" 
                      className="block text-sm font-medium mb-2 text-gray-700 dark:text-gray-300"
                    >
                      Sujet
                    </label>
                    <select
                      id="subject"
                      name="subject"
                      value={formData.subject}
                      onChange={handleChange}
                      required
                      className="w-full px-4 py-3 rounded-lg border border-gray-300 dark:border-dark-700 focus:ring-2 focus:ring-primary-500 focus:border-transparent bg-white dark:bg-dark-900 transition-all"
                    >
                      <option value="">Sélectionnez un sujet</option>
                      {subjects.map((subject, index) => (
                        <option key={index} value={subject.toLowerCase().replace(/\s+/g, '-')}>
                          {subject}
                        </option>
                      ))}
                    </select>
                  </div>
                  
                  <div>
                    <label 
                      htmlFor="message" 
                      className="block text-sm font-medium mb-2 text-gray-700 dark:text-gray-300"
                    >
                      Message
                    </label>
                    <textarea
                      id="message"
                      name="message"
                      value={formData.message}
                      onChange={handleChange}
                      required
                      rows={5}
                      className="w-full px-4 py-3 rounded-lg border border-gray-300 dark:border-dark-700 focus:ring-2 focus:ring-primary-500 focus:border-transparent bg-white dark:bg-dark-900 transition-all resize-none"
                      placeholder="Décrivez votre projet..."
                    />
                  </div>
                  
                  <button
                    type="submit"
                    disabled={isSubmitting}
                    className="w-full bg-primary-500 hover:bg-primary-600 text-white font-medium py-3 px-6 rounded-lg transition-all flex items-center justify-center gap-2 disabled:opacity-70 disabled:cursor-not-allowed"
                  >
                    {isSubmitting ? (
                      <>
                        <Loader2 className="h-5 w-5 animate-spin" />
                        Envoi en cours...
                      </>
                    ) : (
                      'Envoyer le message'
                    )}
                  </button>
                </div>
              </form>
            )}
          </motion.div>
        </div>
      </div>
    </section>
  );
};

export default Contact;
